#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   p <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_p`:
#
#    p row<tab>s
#
# ...to quickly jump into RowanWeb, for example.

cd "$PROJECTS/$1"
