cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'zero-sh/tap'

brew 'ack'
brew 'apply-user-defaults' #see: github.com/zero-sh/apply-user-defaults
brew 'cocoapods'
brew 'coreutils'
brew 'gh'
brew 'go'
brew 'grc'
brew 'guetzli'
brew 'hugo'
brew 'influxdb'
brew 'influxdb-cli'
brew 'jq'
brew 'openssl'
brew 'mas'
brew 'node'
brew 'npm'
brew 'pandoc'
brew 'postgresql@14'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'telnet'
brew 'unar'
brew 'vips'
brew 'wget'
brew 'yarn'
brew 'yt-dlp'

cask '1password'
cask 'asana'
cask 'audacity'
cask 'calibre'
cask 'canva'
cask 'chronosync'
cask 'cursor'
# cask 'docker'  # Removed - not used in production
cask 'dropbox'
cask 'dropbox-capture'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'launchcontrol'
# cask 'mactex'
cask 'macwhisper'
cask 'microsoft-teams'
cask 'notion'
cask 'pastebot'
cask 'rapidapi'
cask 'sf-symbols'
cask 'sketch'
# cask 'slack' - this now installed from Mac App Store
cask 'sonos'
cask 'trader-workstation'
cask 'vlc'
cask 'visual-studio-code'
cask 'zoom'

mas "1Blocker", id: 1365531024
mas "Pixelmator Pro", id: 1289583905
mas "Postico", id: 1031280567
mas "DaisyDisk", id: 411643860
mas "XCode", id: 497799835
mas "Save to Pocket", id: 1477385213
mas "Slack for Desktop", id: 803453959
mas "Bumpr", id: 1166066070
